project:
  type: website
  output-dir: _site

website:
  title: "Math 214: Statistical Laboratory"
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - section: "Datasets"
        contents:
          - text: "Dataset1"
            href: usdata.html
      - section: "Theory"
        contents:
          - text: "Basic Statistics"
            href: basicstatistics.html
          - text: "Basic Probability"
            href: basicprobability.html
          - text: "Discrete Random Variables"
            href: discreteRV.html
          - text: "Continuous Random Variables"
            href: continuousRV.html
          - text: "Sampling Distributions"
            href: samplingdistribution.html
          - text: "Confidence Intervals"
            href: ConfidenceIntervals.html
          - text: "Hypothesis Testing: large Samples"
            href: HTLargeSamples.html            
          - text: "Hypothesis Testing: small Samples"
            href: HTSmallSamples.html  
          - text: "Hypothesis Testing: Two Samples"
            href: HTTwoSamples.html              
      - section: "ShinyApps"
        contents:
          - text: "Sampling Distribution"
            href: sampApp.html
          - text: "Confidence Intervals"
            href: CIApp.html
      - section: "Tutorials"
        contents:
          - text: "R and RStudio"
            href: RandRStudio.html


format:
  html:
    highlight-style: arrow
    fontsize: 1.1em
    code-overflow: wrap
    theme:
      light: [lux, theme-light.scss]
      dark: [superhero, theme-dark.scss]
    css: styles.css
    toc: true
    page-layout: full
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true

filters:
  - shinylive
  - webr

page-footer:
  left: |
    <span class="faux-block">&#169; 2024 Deepak Bastola</span>
  right: |
    <span class="faux-block"><a href="https://github.com/deepbas/">View source on GitHub</a></span>

execute:
  new_session: true
  before_chapter_script: common.R
  freeze: true
  eval: true
  echo: true
  warning: false

language:
  label:
    chapter: "Chapter "
